# -*- mode: ruby -*-
# vi: set ft=ruby :

# README
#
# Getting Started:
# 1. vagrant plugin install vagrant-hostmanager
# 2. vagrant up
# 3. vagrant ssh
#
# This should put you at the control host
#  with access, by name, to other vms

VAGRANT_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.define "puppet-master", primary: true do |master|
    master.vm.box = "bento/ubuntu-18.04"
    master.vm.box_url = "bento/ubuntu-18.04"

    master.vm.network "private_network", ip: "192.168.135.100"
    master.vm.hostname = "puppet-master"
    
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end
  end  
  config.vm.define "agent-centos" do |agent1|
    agent1.vm.box = "centos/7"
    agent1.vm.box_url = "centos/7"

    agent1.vm.network "private_network", ip: "192.168.135.101"
    agent1.vm.hostname = "agent-centos"
    
    agent1.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
  end  
end
