# -*- mode: ruby -*-
# vi: set ft=ruby :

# README
#
# Getting Started:
# 1. vagrant plugin install vagrant-hostmanager
# 2. vagrant up
# 3. vagrant ssh
#
# This should put you at the control host
#  with access, by name, to other vms

VAGRANT_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.define "PuppetMaster", primary: true do |master|
    master.vm.box = "ubuntu-18.04"
    master.vm.box_url = "bento/ubutnu-18.04"

    master.vm.network "private_network", ip: "192.168.135.10"
    master.vm.hostname = "PuppetMaster"
    
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end
  end  
  config.vm.define "agent-1", do |agent-1|
    agent-1.vm.box = "centos-7"
    agent-1.vm.box_url = "centos/7"

    agent-1.vm.network "private_network", ip: "192.168.135.11"
    agent-1.vm.hostname = "CentOS-7"
    
    agent-1.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end
  end  
end
