---
- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
  notify: apt_update

- name: Install list of packages
  apt:
    name: ['apt-transport-https','ca-certificates','curl','software-properties-common','docker-ce']
    state: present
    update_cache: yes

- name: Docker post installation tasks
  group:
    name: "{{docker_group}}"
    state: present

- name: Add user to a docker group
  user: name="{{username}}" groups="{{docker_group}}" append=yes
